name: Create function app repo
on:
  workflow_dispatch:
    inputs:
      c8-report-token:
        description: "C8 Report Token"
      repoName:
        description: "Name of the repo to create"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Report status back to C8
        run: |
          echo "repo name: ${{ inputs.repoName }}"
          STARTED_AT=$(date -Iseconds)
          curl -X POST \
          -H "c8-report-token: ${{ inputs.c8-report-token }}" \
          -H "Content-Type: application/json" \
          https://app.configure8.io/self-service/api/v1/reports/webhook \
          -d "{ \"status\": \"complete\",  \"startedAt\": \"$STARTED_AT\"}" \
