name: Create function app repo
on:
  workflow_dispatch:
    inputs:
      c8-report-token:
        description: "C8 Report Token"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world! ${{ inputs.c8-report-token }}"
