name: Create function to store secrets in created repos
on:
  workflow_dispatch:
    inputs:
      c8-report-token:
        description: "C8 Report Token"
      jump-token:
        description: "Jump token to login to Terraform"
      az-credentials:
        description: "Azure credentials to login to Azure"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #   sushantsahu1987/04-test-secret-management
    #   - name: Create Fn App Repo
    #     run: |
    #       REPO_NAME="${{ inputs.repoFnAppName }}"
    #       TEMPLATE_OWNER="sushantsahu1987"
    #       TEMPLATE_REPO="template-node-function-app"

    #       gh repo create --public $REPO_NAME --template $TEMPLATE_OWNER/$TEMPLATE_REPO
    #     env:
    #       GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Print Inputs
        run: |
          echo "jump-token: ${{ inputs.jump-token }}"
          echo "az-credentials: ${{ inputs.az-credentials }}"

      - name: Report status back to C8
        run: |
          STARTED_AT=$(date -Iseconds)
          curl -X POST \
          -H "c8-report-token: ${{ inputs.c8-report-token }}" \
          -H "Content-Type: application/json" \
          https://app.configure8.io/self-service/api/v1/reports/webhook \
          -d "{ \"status\": \"complete\",  \"startedAt\": \"$STARTED_AT\"}" \
